language: php

dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.3
    - php: nightly

  include:
    - php: 7.1
      env: PHPCS=1 COVERAGE=1 PHPSTAN=0
    - php: 7.2
      env: PHPCS=1 COVERAGE=0 PHPSTAN=0
    - php: 7.3
      env: PHPCS=1 COVERAGE=0 PHPSTAN=0
    - php: nightly
      env: PHPCS=1 COVERAGE=0 PHPSTAN=0

install:
  - ./bin/phpserv >/dev/null 2>&1 &
  - ./bin/composer validate
  - ./bin/composer install --no-interaction --no-progress --no-suggest
  - mkdir -p build/test-coverage build/test-results
  - ./bin/build app:install CHOWN_USER=$USER,CHGRP_GROUP=$USER,DB_NAME=app,DB_ADMIN_USER=root,DB_USER=root

script:
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs; fi
  - ./vendor/bin/phpunit --group example --no-coverage
  - if [[ $COVERAGE = 0 ]]; then ./vendor/bin/phpunit --exclude-group example --no-coverage; fi
  - if [[ $COVERAGE = 1 ]]; then ./vendor/bin/phpunit --exclude-group example; fi
  - if [[ $PHPSTAN = 1 ]]; then ./vendor/bin/phpstan analyse; fi

notifications:
  email:
    - webdev@qobocloud.com
