language: php
    
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - composer install
    - ./vendor/bin/phake app:install

before_script:
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.0.jar
    - php -S localhost:8000 > /dev/null 2>&1 &
    - java -jar selenium-server-standalone-2.49.0.jar > /dev/null 2>&1 &
    - sleep 30 

script: 
    - ./vendor/bin/phpunit --group example
    - ./vendor/bin/phpunit --exclude-group example

