language: php
    
php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

install:
    - ./bin/composer install --no-interaction --no-progress
    - ./vendor/bin/phake app:install CHOWN_USER=root CHGRP_GROUP=root DB_NAME=app DB_ADMIN_USER=root DB_USER=root

before_script:
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    - java -jar selenium-server-standalone-2.53.0.jar > /dev/null 2>&1 &
    - bin/phpserv >/dev/null 2>&1 &
    - sleep 30 

script: 
    - ./vendor/bin/phpunit --group example
    - ./vendor/bin/phpunit --exclude-group example

