language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - ./bin/composer install --no-interaction --no-progress --no-suggest
    - ./vendor/bin/phake app:install CHOWN_USER=$USER CHGRP_GROUP=$USER DB_NAME=app DB_ADMIN_USER=root DB_USER=root

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - wget -O /tmp/selenium-server.jar https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
    - java -jar /tmp/selenium-server.jar > /dev/null 2>&1 &
    - ./bin/phpserv >/dev/null 2>&1 &
    - sleep 30

script:
    - ./vendor/bin/phpunit --group example
    - ./vendor/bin/phpunit --exclude-group example
    - ./vendor/bin/phpcs
