sudo: true
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

install:
  - ./bin/phpserv >/dev/null 2>&1 &
  - ./bin/composer validate --strict
  - ./bin/composer install --no-interaction --no-progress --no-suggest
  - ./bin/build app:install CHOWN_USER=$USER,CHGRP_GROUP=$USER,DB_NAME=app,DB_ADMIN_USER=root,DB_USER=root

script:
  - ./vendor/bin/phpunit --group example --no-coverage
  - ./vendor/bin/phpunit --exclude-group example
  - ./vendor/bin/phpcs

notifications:
  email:
    - webdev@qobocloud.com
