image: smartapps/bitbucket-pipelines-php-mysql

pipelines:
  default:
    - step:
        script:
          - service mysql start
          - mkdir ~/.ssh
          - echo $MY_SSH_KEY | base64 --decode -i > ~/.ssh/id_rsa
          - echo > ~/.ssh/known_hosts
          - ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
          - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          - chmod -R u+rwX,go-rwX ~/.ssh
          - ./bin/composer install --no-interaction --no-progress --no-suggest
          - ./vendor/bin/phake app:install CHOWN_USER=$USER CHGRP_GROUP=$USER DB_NAME=app DB_ADMIN_USER=root DB_ADMIN_PASS=root DB_USER=root DB_PASS=root
          - ./vendor/bin/phpunit --group example
          - ./vendor/bin/phpunit --exclude-group example
          - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
          - ./vendor/bin/phpcs --colors -p --extensions=php --standard=vendor/wp-coding-standards/wpcs/WordPress webroot/custom-themes/
