image: smartapps/bitbucket-pipelines-php-mysql

pipelines:
  default:
    - step:
        script:
          - service mysql start
          - ./bin/composer install --no-interaction --no-progress
          - ./vendor/bin/phake app:install DB_ADMIN_USER=root DB_ADMIN_PASS=root DB_USER=root DB_USER=root DB_NAME=app
          - ./vendor/bin/phpunit --group example
          - ./vendor/bin/phpunit --exclude-group example
